# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    mrobot_arm_hook_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mrobot_arm_hook_controller:
  ros__parameters:
    joints:
      - Arm1_Joint
      - Arm2_Joint
      - Arm3_Joint
      - Arm4_Joint
      - Arm5_Joint
      - Arm6_Joint
      - Arm7_Joint
      - Arm8_Joint
      - Arm9_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity